test1:test1.cpp tinyxml2.cpp tinyxml2.h
	g++ -o test1 test1.cpp tinyxml2.cpp
test2:test2.cpp tinyxml2.cpp tinyxml2.h test2.xml
	g++ -o test2 test2.cpp tinyxml2.cpp
test3:test3.cpp tinyxml2.cpp tinyxml2.h test3.xml
	g++ -o test3 test3.cpp tinyxml2.cpp
test4:test4.cpp tinyxml2.cpp tinyxml2.h test4.xml
	g++ -o test4 test4.cpp tinyxml2.cpp
test5:test5.cpp tinyxml2.cpp tinyxml2.h test2.xml MyXml.cpp MyXml.h Parser.cpp Parser.h
	g++ -o test5 test5.cpp tinyxml2.cpp MyXml.cpp Parser.cpp
clean:
	del *.exe